dist: bionic
sudo: required
language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - g++-8
      - cmake
      - python3
      - ninja-build

script:
  - ln -s /usr/bin/gcc-8 /usr/local/bin/gcc
  - ln -s /usr/bin/g++-8 /usr/local/bin/g++
  - export CC=/usr/bin/gcc-8
  - export CXX=/usr/bin/g++-8
  # Check versions of gcc, g++ and cmake
  - gcc -v && g++ -v && cmake --version
  - mkdir build && cd build
  - cmake -G Ninja
  - ninja all
  # Run your build commands next