dist: bionic
sudo: required
language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - g++-8
      - cmake
      - python3
      - ninja-build
      - python3-venv

script:
  - export CC=/usr/bin/gcc-8
  - export CXX=/usr/bin/g++-8
  # Check versions of gcc, g++ and cmake
  - gcc-8 -v && g++-8 -v && cmake --version
  - mkdir build && cd build
  - cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release 
  - ninja all
  # Run your build commands next